import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:3300/fr', { waitUntil: 'networkidle' });
await page.waitForTimeout(2000);
const total = await page.locator('.reveal-on-scroll').count();
const visible = await page.locator('.reveal-on-scroll.is-visible').count();
console.log('total reveal els:', total, 'is-visible:', visible);
const h1Opacity = await page.locator('section h1').first().evaluate(el => getComputedStyle(el.closest('.reveal-on-scroll')).opacity);
console.log('h1 wrapper computed opacity:', h1Opacity);
await browser.close();
