import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const msgs = [];
page.on('console', m => msgs.push(`[${m.type()}] ${m.text()}`));
page.on('pageerror', e => msgs.push(`[pageerror] ${e.message}`));
await page.goto('http://localhost:3300/fr', { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
const h1 = page.locator('section h1').first();
const visible = await h1.isVisible().catch(() => 'ERR');
const cls = await h1.evaluate(el => el.closest('.reveal-on-scroll')?.className).catch(()=>'n/a');
const htmlClass = await page.evaluate(() => document.documentElement.className);
console.log('html class:', htmlClass);
console.log('H1 visible:', visible, 'reveal class:', cls);
console.log('---console/page messages---');
console.log(msgs.join('\n'));
await browser.close();
